export const SEARCH_BY_INGREDIENT_REQUEST = "SEARCH_BY_INGREDIENT_REQUEST";
export const SEARCH_BY_INGREDIENT_SUCCESS = "SEARCH_BY_INGREDIENT_SUCCESS";
export const SEARCH_BY_INGREDIENT_FAIL = "SEARCH_BY_INGREDIENT_FAIL";

export const GET_MEAL_DETAILS_REQUEST = "GET_MEAL_DETAILS_REQUEST";
export const GET_MEAL_DETAILS_SUCCESS = "GET_MEAL_DETAILS_SUCCESS";
export const GET_MEAL_DETAILS_FAIL = "GET_MEAL_DETAILS_FAIL";
