export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const GET_MEAL_DETAILS_REQUEST = "GET_MEAL_DETAILS_REQUEST";
export const GET_MEAL_DETAILS_SUCCESS = "GET_MEAL_DETAILS_SUCCESS";
export const GET_MEAL_DETAILS_FAIL = "GET_MEAL_DETAILS_FAIL";

export const SET_SEARCH_PARAM = "SET_SEARCH_PARAM";
export const SET_SEARCH_PARAM_ERROR = "SET_SEARCH_PARAM_ERROR";

export const SAVE_RECIPE_REQUEST = "SAVE_RECIPE_REQUEST";
export const SAVE_RECIPE_SUCCESS = "SAVE_RECIPE_SUCCESS";
export const SAVE_RECIPE_ERROR = "SAVE_RECIPE_ERROR";

export const DELETE_RECIPE_REQUEST = "DELETE_RECIPE_REQUEST";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_ERROR = "DELETE_RECIPE_ERROR";
