export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const GET_MEAL_DETAILS_REQUEST = "GET_MEAL_DETAILS_REQUEST";
export const GET_MEAL_DETAILS_SUCCESS = "GET_MEAL_DETAILS_SUCCESS";
export const GET_MEAL_DETAILS_FAIL = "GET_MEAL_DETAILS_FAIL";

export const SET_SEARCH_PARAM = "SET_SEARCH_PARAM";
export const SET_SEARCH_PARAM_ERROR = "SET_SEARCH_PARAM_ERROR";
